from __future__ import annotations

from sqlmodel import select

from app.models import (
    LogModel,
    TraceModel,
    SpanModel,
    ExperimentRunResultModel,
    ExperimentRunModel,
    ExperimentVersionModel,
    ExperimentModel,
)

def _project_spans_stmt():
    return select(SpanModel).join(TraceModel, SpanModel.trace_id == TraceModel.id)


def _experiment_outputs_stmt():
    return (
        select(ExperimentRunResultModel)
        .join(ExperimentRunModel, ExperimentRunResultModel.run_id == ExperimentRunModel.id)
        .join(ExperimentVersionModel, ExperimentRunModel.experiment_version_id == ExperimentVersionModel.id)
        .join(ExperimentModel, ExperimentVersionModel.experiment_id == ExperimentModel.id)
    )


SHAPES = {
    "project_logs": {
        "model": LogModel,
        "param_filters": {"project_id": LogModel.project_id},
        "fields": {
            "id": LogModel.id,
            "project_id": LogModel.project_id,
            "trace_id": LogModel.trace_id,
            "span_id": LogModel.span_id,
            "level": LogModel.level,
            "event_type": LogModel.event_type,
            "status": LogModel.status,
            "message": LogModel.message,
            "timestamp": LogModel.timestamp,
            "latency_ms": LogModel.latency_ms,
            "prompt_tokens": LogModel.prompt_tokens,
            "completion_tokens": LogModel.completion_tokens,
            "total_tokens": LogModel.total_tokens,
            "cost": LogModel.cost,
            "model": LogModel.model,
            "provider": LogModel.provider,
            "attributes": LogModel.attributes,
            "log_metadata": LogModel.log_metadata,
            "created_at": LogModel.created_at,
        },
        "field_types": {
            "id": "string",
            "project_id": "string",
            "trace_id": "string",
            "span_id": "string",
            "level": "string",
            "event_type": "string",
            "status": "string",
            "message": "string",
            "model": "string",
            "provider": "string",
            "timestamp": "number",
            "latency_ms": "number",
            "prompt_tokens": "number",
            "completion_tokens": "number",
            "total_tokens": "number",
            "cost": "number",
            "created_at": "number",
        },
        "filter_fields": {
            "id",
            "project_id",
            "trace_id",
            "span_id",
            "level",
            "event_type",
            "status",
            "message",
            "timestamp",
            "latency_ms",
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "cost",
            "model",
            "provider",
            "created_at",
        },
        "default_sort": ("timestamp", "desc"),
    },
    "project_traces": {
        "model": TraceModel,
        "param_filters": {"project_id": TraceModel.project_id},
        "fields": {
            "id": TraceModel.id,
            "project_id": TraceModel.project_id,
            "parent_trace_id": TraceModel.parent_trace_id,
            "trace_group_id": TraceModel.trace_group_id,
            "input_span_id": TraceModel.input_span_id,
            "output_span_id": TraceModel.output_span_id,
            "timestamp": TraceModel.timestamp,
            "total_latency": TraceModel.total_latency,
            "total_cost": TraceModel.total_cost,
            "total_tokens": TraceModel.total_tokens,
            "status": TraceModel.status,
            "tags": TraceModel.tags,
        },
        "field_types": {
            "id": "string",
            "project_id": "string",
            "parent_trace_id": "string",
            "trace_group_id": "string",
            "input_span_id": "string",
            "output_span_id": "string",
            "status": "string",
            "timestamp": "number",
            "total_latency": "number",
            "total_cost": "number",
            "total_tokens": "number",
        },
        "filter_fields": {
            "id",
            "project_id",
            "parent_trace_id",
            "trace_group_id",
            "input_span_id",
            "output_span_id",
            "timestamp",
            "total_latency",
            "total_cost",
            "total_tokens",
            "status",
        },
        "default_sort": ("timestamp", "desc"),
    },
    "project_spans": {
        "model": SpanModel,
        "base_stmt": _project_spans_stmt,
        "param_filters": {"project_id": TraceModel.project_id},
        "fields": {
            "id": SpanModel.id,
            "project_id": TraceModel.project_id,
            "trace_id": SpanModel.trace_id,
            "parent_id": SpanModel.parent_id,
            "name": SpanModel.name,
            "type": SpanModel.type,
            "start_time": SpanModel.start_time,
            "end_time": SpanModel.end_time,
            "status": SpanModel.status,
            "error_message": SpanModel.error_message,
            "metrics": SpanModel.metrics,
            "attributes": SpanModel.attributes,
            "tags": SpanModel.tags,
            "input": SpanModel.input,
            "output": SpanModel.output,
        },
        "field_types": {
            "id": "string",
            "project_id": "string",
            "trace_id": "string",
            "parent_id": "string",
            "name": "string",
            "type": "string",
            "status": "string",
            "start_time": "number",
            "end_time": "number",
        },
        "filter_fields": {
            "id",
            "project_id",
            "trace_id",
            "parent_id",
            "name",
            "type",
            "status",
            "start_time",
            "end_time",
        },
        "default_sort": ("start_time", "desc"),
    },
    "experiment_outputs": {
        "model": ExperimentRunResultModel,
        "base_stmt": _experiment_outputs_stmt,
        "param_filters": {"experiment_id": ExperimentModel.id},
        "fields": {
            "id": ExperimentRunResultModel.id,
            "experiment_id": ExperimentModel.id,
            "project_id": ExperimentModel.project_id,
            "experiment_version_id": ExperimentRunModel.experiment_version_id,
            "run_id": ExperimentRunResultModel.run_id,
            "run_status": ExperimentRunModel.status,
            "dataset_row_id": ExperimentRunResultModel.dataset_row_id,
            "latency_ms": ExperimentRunResultModel.latency_ms,
            "output": ExperimentRunResultModel.output,
            "scores": ExperimentRunResultModel.scores,
            "created_at": ExperimentRunResultModel.created_at,
        },
        "field_types": {
            "id": "string",
            "experiment_id": "string",
            "project_id": "string",
            "experiment_version_id": "string",
            "run_id": "string",
            "run_status": "string",
            "dataset_row_id": "string",
            "latency_ms": "number",
            "created_at": "number",
        },
        "filter_fields": {
            "id",
            "experiment_id",
            "project_id",
            "experiment_version_id",
            "run_id",
            "run_status",
            "dataset_row_id",
            "latency_ms",
            "created_at",
        },
        "default_sort": ("created_at", "desc"),
    },
}
SHAPES["experiment_logs"] = SHAPES["experiment_outputs"]
